
---
apiVersion: v1alpha1
kind: Pipeline
metadata:
  name: dex
  namespace: acaleph
spec:
  selector:
    matchLabels:
      app: acaleph
  template:
    metadata:
      name: acaleph
      labels:
        app: dex
    stages:
      - name: Build Image
        type: docker_build
